
student_count = 11
puts "The student of the academy"
puts "-----------------"
puts "Bob Smith"
puts "John Brown"
puts "Tracy Beaker"
puts "Hutch"
puts "Starskey"
puts "Donald Duck"
puts "Billy Bonds"
puts "Trevor Brooking"
puts "Pat Holland"
puts "John Lyall"
puts "Alvin Martin"
puts "Overall we have #{student_count} great students"
